# -*- mode: sparql -*-
#title:4x4 sudoku using VALUES
SELECT ?C11 ?C12 ?C13 ?C14 ?C21 ?C22 ?C23 ?C24 ?C31 ?C32 ?C33 ?C34 ?C41 ?C42 ?C43 ?C44 WHERE {
  VALUES ?C11 { 1 }
  VALUES ?C12 { 1 2 3 4 }
  VALUES ?C13 { 1 2 3 4 }
  VALUES ?C14 { 1 2 3 4 }
  VALUES ?C21 { 1 2 3 4 }
  VALUES ?C22 { 2 }
  VALUES ?C23 { 1 2 3 4 }
  VALUES ?C24 { 1 2 3 4 }
  VALUES ?C31 { 1 2 3 4 }
  VALUES ?C32 { 1 2 3 4 }
  VALUES ?C33 { 4 }
  VALUES ?C34 { 1 2 3 4 }
  VALUES ?C41 { 1 2 3 4 }
  VALUES ?C42 { 1 2 3 4 }
  VALUES ?C43 { 1 2 3 4 }
  VALUES ?C44 { 3 }

  FILTER(?C11 != ?C12 && ?C11 != ?C13 && ?C11 != ?C14
                      && ?C12 != ?C13 && ?C12 != ?C14
                                      && ?C13 != ?C14) .
  FILTER(?C21 != ?C22 && ?C21 != ?C23 && ?C21 != ?C24
                      && ?C22 != ?C23 && ?C22 != ?C24
                                      && ?C23 != ?C24) .
  FILTER(?C31 != ?C32 && ?C31 != ?C33 && ?C31 != ?C34
                      && ?C32 != ?C33 && ?C32 != ?C34
                                      && ?C33 != ?C34) .
  FILTER(?C41 != ?C42 && ?C41 != ?C43 && ?C41 != ?C44
                      && ?C42 != ?C43 && ?C42 != ?C44
                                      && ?C43 != ?C44) .

  FILTER(?C11 != ?C21 && ?C11 != ?C31 && ?C11 != ?C41
                      && ?C21 != ?C31 && ?C21 != ?C41
                                      && ?C31 != ?C41) .
  FILTER(?C12 != ?C22 && ?C12 != ?C32 && ?C12 != ?C42
                      && ?C22 != ?C32 && ?C22 != ?C42
                                      && ?C32 != ?C42) .
  FILTER(?C13 != ?C23 && ?C13 != ?C33 && ?C13 != ?C43
                      && ?C23 != ?C33 && ?C23 != ?C43
                                      && ?C33 != ?C43) .
  FILTER(?C14 != ?C24 && ?C14 != ?C34 && ?C14 != ?C44
                      && ?C24 != ?C34 && ?C24 != ?C44
                                      && ?C34 != ?C44) .

  FILTER(?C11 != ?C12 && ?C11 != ?C21 && ?C11 != ?C22
                      && ?C12 != ?C21 && ?C12 != ?C22
                                      && ?C21 != ?C22) .
  FILTER(?C31 != ?C32 && ?C31 != ?C41 && ?C31 != ?C42
                      && ?C32 != ?C41 && ?C32 != ?C42
                                      && ?C41 != ?C42) .

  FILTER(?C13 != ?C14 && ?C13 != ?C23 && ?C13 != ?C24
                      && ?C13 != ?C23 && ?C13 != ?C24
                                      && ?C23 != ?C24) .
  FILTER(?C33 != ?C34 && ?C33 != ?C43 && ?C33 != ?C44
                      && ?C34 != ?C43 && ?C34 != ?C44
                                      && ?C43 != ?C44) .
}
