# -*- mode: sparql -*-
#title:musical genres with the most bands and musicians
SELECT ?genreLabel ?performers WHERE {
{ SELECT ?genre (COUNT(DISTINCT ?performer) AS ?performers) WHERE {
  ?genre wdt:P31/wdt:P279* wd:Q188451 ;
         ^wdt:P136 ?performer .
  {{ ?performer wdt:P31/wdt:P279* wd:Q215380 } UNION {
    ?performer (wdt:P31/wdt:P279*)|wdt:P106 wd:Q639669 }}

} GROUP BY ?genre ORDER BY DESC(?performers) LIMIT 42 }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} ORDER BY DESC(?performers)
