# -*- mode: sparql -*-
#title:people who have won more than one nobel prize
SELECT ?personLabel ?prizeALabel (YEAR(?yearA) AS ?ya) ?prizeBLabel (YEAR(?yearB) AS ?yb) WHERE {
  ?prizeA wdt:P361 wd:Q7191 .
  ?prizeB wdt:P361 wd:Q7191 .
  ?person p:P166 ?stmtA, ?stmtB ;
          wdt:P31 wd:Q5 .
  ?stmtA ps:P166 ?prizeA ;
         pq:P585 ?yearA .
  ?stmtB ps:P166 ?prizeB ;
         pq:P585 ?yearB .
  FILTER(?yearA <= ?yearB && ?stmtA != ?stmtB)

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
  }
