# most influential bands and musicians
SELECT ?influencer ?influencerLabel
       (COUNT(DISTINCT ?influenced) AS ?influences) WHERE {
  {{ ?influencer wdt:P31/wdt:P279* wd:Q215380 } UNION          # a band
   { ?influencer ((wdt:P31/wdt:P279*)|wdt:P106) wd:Q639669 }}  # a musician
  ?influencer ^wdt:P737 ?influenced .                          # influenced-by
  {{ ?influenced wdt:P31/wdt:P279* wd:Q215380 } UNION          # a band
   { ?influenced ((wdt:P31/wdt:P279*)|wdt:P106) wd:Q639669 }}  # a musician
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  } GROUP BY ?influencer ?influencerLabel ORDER BY DESC(?influences) LIMIT 15